USE [master]
GO
/****** Object:  Database [DCSondage]    Script Date: 05/02/2018 09:10:39 ******/
CREATE DATABASE [DCSondage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DCSondage', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DCSondage.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DCSondage_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DCSondage_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [DCSondage] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DCSondage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DCSondage] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DCSondage] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DCSondage] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DCSondage] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DCSondage] SET ARITHABORT OFF 
GO
ALTER DATABASE [DCSondage] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DCSondage] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DCSondage] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DCSondage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DCSondage] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DCSondage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DCSondage] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DCSondage] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DCSondage] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DCSondage] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DCSondage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DCSondage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DCSondage] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DCSondage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DCSondage] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DCSondage] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DCSondage] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DCSondage] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DCSondage] SET  MULTI_USER 
GO
ALTER DATABASE [DCSondage] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DCSondage] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DCSondage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DCSondage] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DCSondage] SET DELAYED_DURABILITY = DISABLED 
GO
USE [DCSondage]
GO
/****** Object:  Table [dbo].[choix]    Script Date: 05/02/2018 09:10:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[choix](
	[numChoix] [int] IDENTITY(1,1) NOT NULL,
	[nomChoix] [nvarchar](max) NOT NULL,
	[numSondage] [int] NOT NULL,
 CONSTRAINT [PK_choix] PRIMARY KEY CLUSTERED 
(
	[numChoix] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[lien]    Script Date: 05/02/2018 09:10:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[lien](
	[numLien] [int] IDENTITY(1,1) NOT NULL,
	[adresseLien] [varchar](max) NOT NULL,
	[numSondage] [int] NOT NULL,
 CONSTRAINT [PK_lien] PRIMARY KEY CLUSTERED 
(
	[numLien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[sondage]    Script Date: 05/02/2018 09:10:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sondage](
	[numSondage] [int] IDENTITY(1,1) NOT NULL,
	[questionSondage] [text] NOT NULL,
	[typeSondage] [int] NOT NULL,
 CONSTRAINT [PK_sondage] PRIMARY KEY CLUSTERED 
(
	[numSondage] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[votant]    Script Date: 05/02/2018 09:10:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[votant](
	[numVotant] [int] IDENTITY(1,1) NOT NULL,
	[adresseIp] [varchar](50) NULL,
 CONSTRAINT [PK_votant] PRIMARY KEY CLUSTERED 
(
	[numVotant] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[vote]    Script Date: 05/02/2018 09:10:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[vote](
	[numVote] [int] IDENTITY(1,1) NOT NULL,
	[nbVote] [int] NOT NULL,
	[nbVotant] [int] NULL,
	[numChoix] [int] NOT NULL,
	[numVotant] [int] NOT NULL,
 CONSTRAINT [PK_vote] PRIMARY KEY CLUSTERED 
(
	[numVote] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[choix]  WITH CHECK ADD  CONSTRAINT [FK_choix_sondage1] FOREIGN KEY([numSondage])
REFERENCES [dbo].[sondage] ([numSondage])
GO
ALTER TABLE [dbo].[choix] CHECK CONSTRAINT [FK_choix_sondage1]
GO
ALTER TABLE [dbo].[lien]  WITH CHECK ADD  CONSTRAINT [FK_lien_sondage1] FOREIGN KEY([numSondage])
REFERENCES [dbo].[sondage] ([numSondage])
GO
ALTER TABLE [dbo].[lien] CHECK CONSTRAINT [FK_lien_sondage1]
GO
ALTER TABLE [dbo].[vote]  WITH CHECK ADD  CONSTRAINT [FK_vote_choix] FOREIGN KEY([numChoix])
REFERENCES [dbo].[choix] ([numChoix])
GO
ALTER TABLE [dbo].[vote] CHECK CONSTRAINT [FK_vote_choix]
GO
ALTER TABLE [dbo].[vote]  WITH CHECK ADD  CONSTRAINT [FK_vote_votant] FOREIGN KEY([numVotant])
REFERENCES [dbo].[votant] ([numVotant])
GO
ALTER TABLE [dbo].[vote] CHECK CONSTRAINT [FK_vote_votant]
GO
USE [master]
GO
ALTER DATABASE [DCSondage] SET  READ_WRITE 
GO
